---
title: "Parse Med Rd XML"
author: "Poojyatha"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
pacman::p_load(xml2, tidyverse, evaluate, collapse, htmltidy, janitor)
```

Purpose

:   Parse the RxNorm XML table

Tables

-   namespace
-   referencedNamespace
-   proptype
-   qualtype
-   term
-   assntype
-   association
-   concept
    -   property
    -   synonym

## Load XML

```{r}
d <- xml2::read_xml(here::here("inst/Core_MEDRT_XML/Core_MEDRT_2022.05.02_XML.xml"))
```

```{r}
d
```

## Namespace

```{r}
namespace <- xml_find_all(d, 'namespace')
namespace
```

```{r}
namespace %>% htmltidy::xml_view()
```

```{r}
n <-  namespace  %>% 
  as_list() %>% 
  tibble(c = .) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  %>% 
  unnest_longer(col=everything())

n
```

```{r}
n <-  namespace  %>% 
  as_list() %>% 
  tibble(c = .) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  %>%  
  unnest_longer(col = everything())

 n
```

```{r}
data.table::fwrite(n,here::here('data','namespace.csv'))
```

```{r}
xname <- data.table::fread(here::here('data','namespace.csv'))

#dat0 <-  data.table::fread(here::here('data','dts_associationtype.csv'))
```

## referencedNamespace

```{r}
referencedNamespace <- xml_find_all(d, 'referencedNamespace')
```

```{r}
referencedNamespace  %>% htmltidy::html_view()
```

```{r}
 r <-  referencedNamespace %>% 
  as_list() %>% tibble(c = .) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  %>% 
  unnest_longer(col = everything())

r
```

```{r}
data.table::fwrite(r,here::here('data','referencednamespace.csv'))
```

```{r}
xrefname <- data.table::fread(here::here('data','referencednamespace.csv'))
```

```{r}
xrefname %>% head()
```

## proptype

```{r}
proptype <- xml_find_all(d, 'proptype')
```

```{r}
proptype %>% htmltidy::xml_view()
```

```{r}
p <- proptype %>% 
  as_list() %>% 
  tibble(c = .) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  %>%  
  unnest_longer(col = everything())

p
```

```{r}
data.table::fwrite(p,here::here('data','proptype.csv'))
```

```{r}
xproptype <- data.table::fread(here::here('data','proptype.csv'))
```

## qualtype

```{r}
qualtype <-  xml_find_all(d, 'qualtype') 

```

```{r}
q0 <-  

      qualtype %>% 
      as_list() %>% 
      tibble(c = .) %>%
      unnest_wider(col = c) %>%
      janitor::clean_names() 
      
q0 %>% head()
```

```{r}
q <-  q0 %>% 
  unnest_longer(col = everything())

q %>% head()
```

```{r}
data.table::fwrite(q,here::here('data','qualtype.csv'))
```

```{r}
xqualtype <- data.table::fread(here::here('data','qualtype.csv'))
```

## term

```{r}
term <- xml_find_all(d, 'term')
term %>% head()
```

```{r}
term[1:4] %>% htmltidy::html_view() 
```

```{r}
t <-  term %>% 
  as_list() %>% 
  tibble(c1 = .) %>% 
  unnest_wider(col = c1) %>% 
  janitor::clean_names()  %>% 
  unnest_longer(col = everything())

t %>% head()

```

```{r}
data.table::fwrite(t,here::here('data','term.csv'))
```

```{r}
xterm <- data.table::fread(here::here('data','term.csv'))
```

## assntype

```{r}
assntype <- xml_find_all(d, 'assntype')
```

```{r}
assntype[1:3] %>% htmltidy::xml_view()
```

```{r}
A0 <-  dterm <- xml_find_all(d, 'term') 
A0 %>% head()
```

```{r}
A1<- A0 %>% 
  as_list() %>% 
  tibble(c1 = .) %>% 
  unnest_wider(col = c1) %>% 
  unnest_longer( col = everything())


A1 %>% head()
```

```{r}
data.table::fwrite(A1,here::here('data','assn_type.csv'))
```

```{r}
xassntype <- data.table::fread(here::here('data','assn_type.csv'))
```

## association

```{r}
assn <-  xml_find_all(d, 'association')  
assn
```

```{r}
assn[1:10] %>% htmltidy::xml_view()
```

```{r, message=FALSE}
a0<- assn %>% as_list() %>% tibble(c = .)
a1<-a0 %>% 
  rowwise() %>% 
  #mutate(lengthc = length(c)) %>%
  ungroup() %>% 
  #filter(lengthc != 9) %>% 
  #select(-lengthc) %>% 
  #slice(1) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  %>%
  pivot_longer(starts_with('qualifier'), names_to = 'qualifiername', values_to = 'qualifier') %>% 
  
   unnest_longer(col = qualifier) %>% 
  
  rename(namespacetop = namespace,
         nametop = name) %>% 
  filter(!is.na(qualifier_id)) %>% 
  pivot_wider(names_from = qualifier_id, values_from = qualifier, names_prefix = 'qualifier_') %>% 
  select(-qualifiername) %>% 
  
  unnest(col = everything()) %>% 
  unnest(col = everything())

```

```{r}
xassn %>% head()

```

```{r}
names(xassn)
xassn %>% 
  mutate(numpart = str_extract(to_name, "\\[.*\\]"),
         to_code = parse_number(numpart)) %>% 
  select(-numpart) %>% 
  head()
```

```{r}
names(xassn)
xassn %>% 
  mutate(fnnumpart = str_extract(from_name, "\\[.*\\]"),
         from_code = parse_number(fnnumpart)) %>% 
    mutate(numpart = str_extract(to_name, "\\[.*\\]"),
         to_code = parse_number(numpart)) %>% 
  select(-fnnumpart,-numpart) %>% 
  head()
```

```{r}
a1 %>% 
  group_by(qualifier_namespace, qualifier_name, qualifier_value) %>% 
  summarise(count = n(), .groups = 'drop')
```

```{r}
data.table::fwrite(a1,here::here('data','association.csv'))
```

```{r}
xassn <- data.table::fread(here::here('data','association.csv'))
```

## concept

```{r}
concept <-  xml_find_all(d, 'concept')  
concept[1:20]
```

```{r}

```

```{r}
concept[1:10] %>% htmltidy::xml_view()
```

```{r}
c00<- concept %>% as_list() %>% tibble(c = .) 
```

```{r}
c00
```

```{r}
c11<- c00 %>% unnest_wider(col=c)
```

```{r}
c11<- c00 %>% unnest_wider(col=c)

c11 %>% head()


```

```{r}
c11 %>%  unnest_wider(col=everything())
```

### property concept

```{r}
c22<- c11 %>% 
  select(namespace:status, starts_with('property'))

c22
```

```{r}
c22<- c11 %>% 
  select(namespace:status, starts_with('property')) %>%
  pivot_longer(starts_with('property'), names_to = 'propertyname', values_to = 'property') 

c22
```

```{r}
c33 <-  c22 %>%  unnest_longer(col = property) %>% 
  
  select(-propertyname) %>% 
  filter(!is.na(property_id)) %>% 
  pivot_wider(names_from = property_id, values_from = property, names_prefix = 'property_')  %>% 
   unnest_longer(col = everything()) %>% 
  select(-ends_with('id')) %>% 
  unnest(col = starts_with('property')  ) %>% 
  unnest(col = starts_with('property'))

c33

#property concept variable 
```

```{r}
c33 %>% 
  filter(property_name == 'NUI',
         code != property_value)

```

```{r}
c33
```

```{r}
c33 %>% data.table::fwrite(here::here('data','concept_properties.csv'))
```

```{r}
xpropconcept <- data.table::fread(here::here('data','concept_properties.csv'))
```

### concept synonym

```{r}
 s<-c1 %>% 
  select(namespace:status, starts_with('synonym')) %>% 
  pivot_longer(starts_with('synonym'), names_to = 'synonymname', values_to = 'synonym') 

s
```

```{r}
s1<- s %>%  unnest_longer(col = everything()) %>% 
  unnest(col=synonym) %>% 
  unnest(col=synonym) %>% 
  rename(namespace_syn=namespace,name_syn=name) 

s1
```

```{r}
s %>%  unnest_longer(col = everything()) %>% 
  unnest(col=synonym) %>% 
  unnest(col=synonym) %>% 
  rename(namespace_syn=namespace,name_syn=name) %>% 
  pivot_wider(names_from = 'synonym_id',values_from = 'synonym')
```

```{r}
c3<- concept %>% 
  as_list() %>% 
  tibble(c1 = .) %>% 
  unnest_wider(col = c1) %>% 
  janitor::clean_names()  
  #unnest_longer(col = everything())

c3
```

```{r}
a0<- assn[1:1000] %>% as_list() %>% tibble(c = .)
a0 %>% 
  rowwise() %>% 
  mutate(lengthc = length(c)) %>%
  ungroup() %>% 
  filter(lengthc != 9) %>% 
  select(-lengthc) %>% 
  slice(1) %>% 
  unnest_wider(col = c) %>% 
  janitor::clean_names()  
  head(11)
```

## synonym concept

```{r}
 s0<-c11 %>% 
  select(namespace:status, starts_with('synonym')) %>% 
  pivot_longer(starts_with('synonym'), names_to = 'synonymname', values_to = 'synonym') 

s0

```

```{r}
s11<- s0 %>%  unnest_longer(col = everything()) %>% 
  unnest(col=synonym) %>% 
  unnest(col=synonym) %>% 
  rename(namespace_syn=namespace,name_syn=name) 

s11 %>% head()
```

```{r}

s22<- s0 %>%  unnest_longer(col = everything()) %>% 
  unnest(col=synonym) %>% 
  unnest(col=synonym) %>% 
  rename(namespace_syn=namespace,name_syn=name) %>% 
  pivot_wider(names_from = 'synonym_id',values_from = 'synonym') %>% 
  select(-name, -synonymname, -namespace_syn)

s22 %>% head(100)
```

```{r}
s22 %>% 
  filter(preferred == 'false') %>% 
  head(20) %>% 
  select(name_syn, to_name, everything())
```

```{r}
s22 %>% head()
```

```{r}

data.table::fwrite(s22,here::here('data','concept_synonym.csv'))
```

```{r}
con_syn<- data.table::fread(here::here('data','concept_synonym.csv'))
```

```{r}
xsynonymconcept <- data.table::fread(here::here('data','concept_synonym.csv'))
```

## over
