project:
  type: website

website:
  title: "Case Study parsing XML with R"
  navbar:
    left:

      - href: about.qmd
        text: about
      - href: Documentation0.qmd
        text: Internship Summary
      - href: Documentation.qmd
        text: Parsing XML file
      - href: Documentation2.qmd
        text: Merging data
      - href: Documentation3.qmd
        text: All XML to CSV files
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



