project:
  type: website

website:
  title: "Case Study parsing XML with R demonstrated with RxNorm"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: Documentation3.qmd
        text: Parse XML

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



