project:
  type: website

website:
  title: "Case Study parsing XML with R demonstrated with RxNorm"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: Documentation.qmd
        text: Parsing XML file
      - href: Documentation2.qmd
        text: Working with drugs data and patient data
      - href: Documentation3.qmd
        text: List of all the xml-to-CSV files
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



